export const INCREASE_RANK = 'INCREASE_RANK'
export const DECREASE_RANK = 'DECREASE_RANK'
export const ADD_STAR = 'ADD_STAR'
export const REMOVE_STAR = 'REMOVE_STAR'
export const ADD_WIN_STREAK = 'ADD_WIN_STREAK'
export const STOP_WIN_STREAK = 'STOP_WIN_STREAK'
export const RESET_SERIE = 'RESET_SERIE'
export const SET_SERIE_DATA = 'SET_SERIE_DATA'
export const CHOOSE_DECK = 'CHOOSE_DECK'
export const ADD_DECK = 'ADD_DECK'
export const REMOVE_DECK = 'REMOVE_DECK'
export const ADD_DECKTYPE = 'ADD_DECKTYPE'
export const REMOVE_DECKTYPE = 'REMOVE_DECKTYPE'

